### ISSUE TITLE
Cytoscape export for networks

### ISSUE THREAD

**Issue by sdrogers** [glasgowcompbio/ms2ldaviz#35] opened 2016-11-24 12:18 UTC
This would be nice...

**Comment by sdrogers** [comment] 2016-11-24 12:19
And, being able to draw networks and show how many molecules from each file are in each motif

**Comment by joewandy** [comment] 2016-11-24 15:44
We did try to export this to cytoscape before, and i think it was kind of working (@justinjjvanderhooft  remembers?).

As I recall, we still used networkx to draw the graph, then we exported it to some XML-based format which could be loaded into cytoscape. Had to label the graph node and edges attributes correctly for the exported graph to be readable into cytoscape. I'll try to find the codes ..

**Comment by joewandy** [comment] 2018-09-27 12:16
Don't need this anymore.

**Comment by justinjjvanderhooft** [comment] 2018-09-27 14:51
Why? 🙂

**Comment by joewandy** [comment] 2018-09-27 14:52
Do we still want this? 😄

**Comment by justinjjvanderhooft** [comment] 2018-09-27 14:54
Not high prio but why not? 🙂

**Comment by joewandy** [comment] 2021-07-29 09:24
Duplicate of #162

**Closed by joewandy** 2021-07-29 09:24 UTC
